### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by Dissurender** [JetLogged/JetLog#1]
Work with team to implement a base project structure and initialize the main branch prior to feature branching.

---
### Tasks to complete:
- [ ] Get dev environments setup
- [ ] Use Spring Initializer to create outer directories
- [ ] Create React App in View level directory
- [ ] Setup basic actions and standards ie: prettier
